function showOrganelle(){
    var selectedOrganelle = document.getElementById("organelleSelect").value;

    var organelleModels = {
        "Nucleolus": "assets/Nucleolus.glb",
        "Chromatin": "assets/Chromatin.glb",
        "Nuclear Membrane": "assets/NuclearMembrane.glb",
        "RER": "assets/RER.glb",
        "SER": "assets/SER.glb",
        "Ribosome": "assets/Ribosome.glb",
        "Lysosome": "assets/Lysosome.glb",
        "Golgi Apparatus": "assets/GolgiApparatus.glb",
        "Vacuole": "assets/Vacuole.glb",
        "Centrioles": "assets/Centrioles.glb",
        "Mitochondrion": "assets/Mitochondrion.glb",
        "Cytoplasm": "assets/Cytoplasm.glb",
        "Cell Membrane": "assets/CellMembrane.glb"
    }
    var modelURL = organelleModels[selectedOrganelle];

    var organelleModelDiv = document.getElementById("organelleModel");
    organelleModelDiv.innerHTML = `<model-viewer src="${modelURL}" 
    ar ar-modes="webxr scene-viewer quick-look" 
    camera-controls poster="poster.webp" shadow-intensity="1">`;

}

function showText(){
    var selectedOrganelle = document.getElementById("organelleSelect").value;

    var organelleModels = {
        "Nucleolus": "The nucleolus is a prominent substructure found within the nucleus of eukaryotic cells, particularly in animal and plant cells. It is primarily responsible for the assembly of ribosomes, the cellular machinery essential for protein synthesis. The nucleolus contains three main components: fibrillar centers, dense fibrillar components, and granular components, each with specific roles in ribosome production. Ribosomal RNA (rRNA) genes are transcribed and processed in the nucleolus, where ribosomal subunits are also assembled before being transported to the cytoplasm for protein synthesis. The nucleolus plays a crucial role in cellular function by ensuring the efficient production of ribosomes, making it vital for protein synthesis and overall cell growth.",
        "Chromatin": "Chromatin is the material that makes up the nucleus of eukaryotic cells. It consists of DNA molecules wrapped around proteins called histones. Chromatin's primary role is to package and organize the long strands of DNA, enabling it to fit within the confined space of the cell nucleus. It plays a crucial role in gene regulation by controlling access to specific regions of the DNA, which influences the activation or repression of genes. Chromatin can exist in two states: euchromatin, which is loosely packed and allows for gene transcription, and heterochromatin, which is densely packed and represses gene activity. Modifications to histone proteins and DNA within chromatin are essential for regulating gene expression and various cellular processes like development and response to environmental cues.",
        "Nuclear Membrane": "The nuclear membrane, also known as the nuclear envelope, is a double-layered membrane structure that surrounds the nucleus of eukaryotic cells. It serves as a protective barrier, separating the nucleus from the cytoplasm. The nuclear membrane consists of an inner nuclear membrane and an outer nuclear membrane, which are connected at specific points called nuclear pores. These pores allow for controlled communication between the nucleus and the cytoplasm, facilitating the exchange of molecules such as RNA and proteins. During cell division, the nuclear membrane disassembles to enable the proper segregation of genetic material into daughter cells, and it reforms in each daughter cell to protect the genetic material. In summary, the nuclear membrane is a vital cellular structure that safeguards the integrity of the nucleus while permitting regulated molecular interactions.",
        "SER": "The smooth endoplasmic reticulum (SER) is a membrane-bound organelle found in eukaryotic cells. Unlike the rough endoplasmic reticulum (RER), the SER lacks ribosomes on its surface, giving it a smooth appearance. The primary function of the SER is lipid metabolism, including the synthesis of phospholipids and steroids. It also plays a role in detoxification by containing enzymes that process drugs and toxins within the cell. Additionally, the SER stores and releases calcium ions, which are essential for various cellular processes such as muscle contraction and signaling pathways. In summary, the smooth endoplasmic reticulum is primarily responsible for lipid synthesis, detoxification, and calcium regulation in eukaryotic cells.",
        "RER": "The rough endoplasmic reticulum (RER) is a membrane-bound organelle found in eukaryotic cells. It appears rough due to the presence of ribosomes attached to its outer surface, which are responsible for protein synthesis. The RER plays a crucial role in protein production and processing within the cell. As ribosomes translate messenger RNA (mRNA) into proteins, the RER aids in the synthesis of secretory proteins, membrane proteins, and proteins destined for cellular organelles or export. After synthesis, these proteins undergo various post-translational modifications, such as glycosylation and proper folding, within the RER's lumen. Once processed, proteins are then transported to their target destinations, ensuring their functionality within the cell or for secretion outside the cell. In summary, the rough endoplasmic reticulum is a vital organelle primarily responsible for protein synthesis and processing in eukaryotic cells, distinguished by the presence of ribosomes on its surface.",
        "Ribosome": "Ribosomes are fundamental cellular structures found in all living cells, responsible for protein synthesis. They are composed of two subunits, the small and large ribosomal subunits, that work together to read the genetic code carried by messenger RNA (mRNA) and facilitate the assembly of amino acids into polypeptide chains during translation. Ribosomes can be found in two locations within a cell: in the cytoplasm (free ribosomes) and attached to the rough endoplasmic reticulum (membrane-bound ribosomes). They play a central role in translating the genetic information stored in the DNA into functional proteins, which are essential for virtually all cellular functions. In summary, ribosomes are cellular structures crucial for protein synthesis and are integral to the processes that sustain life within cells.",
        "Lysosome": "Lysosomes are membrane-bound organelles found in eukaryotic cells, responsible for cellular digestion and waste management. They contain a variety of enzymes known as hydrolases, which can break down cellular waste, damaged organelles, and foreign substances, including bacteria and viruses. Lysosomes play a critical role in maintaining cellular health by removing and recycling cellular debris, ensuring proper waste disposal. They are involved in processes such as autophagy, where they engulf and degrade old or malfunctioning organelles, and phagocytosis, where they digest materials taken in from the external environment. Lysosomal malfunction can lead to various diseases, such as lysosomal storage disorders, highlighting the essential role of lysosomes in cellular homeostasis and overall health. In summary, lysosomes are vital cellular organelles responsible for waste disposal and maintaining cellular integrity.",
        "Golgi Apparatus": "The Golgi apparatus, also known as the Golgi complex or Golgi body, is a membrane-bound organelle found in eukaryotic cells. It plays a central role in processing, modifying, and sorting proteins and lipids synthesized in the endoplasmic reticulum (ER) for distribution to their final destinations. The Golgi apparatus consists of a series of flattened, stacked membrane sacs called cisternae, organized into a cis face (receiving end) and a trans face (shipping end). As proteins and lipids move through the Golgi, they undergo post-translational modifications such as glycosylation and receive specific molecular tags for targeting. The Golgi apparatus acts as a distribution center, sending these modified molecules to various cellular locations, including lysosomes, the plasma membrane, or for secretion outside the cell. In summary, the Golgi apparatus is a crucial organelle involved in processing and sorting molecules, ensuring their proper function and delivery within the cell and to the external environment.",
        "Vacuole": "The vacuole is a membrane-bound organelle primarily found in plant cells, fungal cells, and some protists. It serves as a versatile and dynamic structure with multiple functions. One of its primary roles is to store water, helping to maintain turgor pressure and support the cell's structural integrity in plant cells. Vacuoles can also store various molecules, including sugars, ions, pigments, and toxins, acting as a reservoir for essential nutrients and waste products. Additionally, they play a role in regulating cell growth and expansion by controlling the flow of water and nutrients. In some plant cells, vacuoles may contain pigments that give flowers and fruits their vibrant colors, serving both aesthetic and protective functions. In summary, the vacuole is a multifunctional organelle involved in storage, structural support, waste management, and pigment distribution in plant and certain other cell types.",
        "Centrioles": "Centrioles are small, cylindrical structures typically found in animal cells, often occurring in pairs near the nucleus within a region called the centrosome. They play a crucial role in cell division, particularly during the process of cell replication known as mitosis, and in the formation of cilia and flagella. During cell division, centrioles organize and anchor the microtubules of the mitotic spindle, ensuring the accurate separation of chromosomes into the daughter cells. While centrioles are essential for cell division, they are not present in all types of cells and are notably absent in plant cells. The centrosome, which contains the centrioles, acts as the cell's microtubule organizing center and plays a vital role in maintaining cell shape and polarity. In summary, centrioles are specialized organelles involved in organizing microtubules and ensuring proper chromosome segregation during cell division in animal cells.",
        "Mitochondrion": "Mitochondria are double-membraned organelles found in eukaryotic cells, often referred to as the powerhouses of the cell due to their central role in energy production. They generate adenosine triphosphate (ATP), the cell's primary energy currency, through a process called oxidative phosphorylation. Mitochondria have their own DNA and can replicate independently, leading to the theory of their evolutionary origin as symbiotic bacteria. These organelles play a critical role in cellular respiration, where they convert glucose and oxygen into ATP, releasing carbon dioxide and water as byproducts. Mitochondria are highly dynamic and can change shape, fuse, or divide to meet the cell's energy demands, making them essential for various cellular functions beyond energy production. In summary, mitochondria are essential organelles responsible for ATP production, cellular respiration, and maintaining cellular energy balance in eukaryotic cells.",
        "Cytoplasm": "Cytoplasm is the jelly-like substance that fills the interior of a cell, surrounding all of its organelles. It is a semi-fluid matrix composed of water, salts, and various molecules, and it provides a medium for chemical reactions to occur within the cell. Cytoplasm plays a critical role in supporting and suspending cellular structures, allowing them to move and interact as needed. It also serves as a site for essential metabolic processes, including glycolysis, which is the initial step of glucose metabolism. Overall, cytoplasm is a vital component of the cell, enabling various cellular functions and serving as the environment where many biochemical reactions take place.",
        "Cell Membrane": "The cell membrane, also known as the plasma membrane, is a thin, semi-permeable barrier that surrounds the outer boundary of all cells. It consists of a lipid bilayer composed of phospholipids, proteins, and other molecules. The primary function of the cell membrane is to regulate the passage of substances in and out of the cell, controlling the cell's internal environment. It selectively allows essential molecules like nutrients and ions to enter the cell while keeping harmful substances out. Additionally, the cell membrane contains receptors and proteins that facilitate communication between the cell and its external environment, enabling cell recognition and signaling processes. In summary, the cell membrane is a crucial component of cells, serving as a protective boundary and a dynamic interface for the exchange of materials and information."
    }
    var modelText = organelleModels[selectedOrganelle];

    var organelleModelDiv = document.getElementById("organelleText");
    organelleModelDiv.innerHTML = modelText;

}